### PR TITLE
2.2.0

### PR DESCRIPTION
**Pull request by notoriouslogank**
Add music player.

### CODE REVIEW

**Comment by notoriouslogank** [comment]
Okay but how do I make it go?

**Review by notoriouslogank — COMMENTED** [review]
Looks good enough for the girls I go out with.

**Review by thenotoriouslogank — APPROVED** [review]
Okay do it.

**Review by thenotoriouslogank — APPROVED** [review]

**Review by thenotoriouslogank — APPROVED** [review]
MERGE YA PIECE O' JUNK

**Pull request merged**
